# ServiceAccount: Provides an identity for pods to interact with the Kubernetes API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa  # Identity name for pods to use
  namespace: default
  labels:
    app: my-app
